# Generated by Django 5.0.6 on 2024-06-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsmsystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveregistrationdata',
            name='address',
            field=models.CharField(default='currentAddress', max_length=30),
        ),
        migrations.AddField(
            model_name='saveregistrationdata',
            name='email',
            field=models.CharField(default='emailid', max_length=30),
        ),
        migrations.AddField(
            model_name='saveregistrationdata',
            name='mobile',
            field=models.CharField(default='1234567890', max_length=30),
        ),
        migrations.AddField(
            model_name='saveregistrationdata',
            name='password',
            field=models.CharField(default='Sameer@1', max_length=30),
        ),
        migrations.AddField(
            model_name='saveregistrationdata',
            name='timezone',
            field=models.CharField(default='UTC', max_length=10),
        ),
        migrations.AlterField(
            model_name='saveregistrationdata',
            name='repeatpassword',
            field=models.CharField(default='Sameer@1', max_length=30),
        ),
    ]
